version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - '3336:3306'
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toor
    depends_on:
      - db

volumes:
  db_data:
